import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/Footer";
import { AppWrapper } from "@/context/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="mx-10 my-4">
      <body className={inter.className}>
        <AppWrapper>
          {children}
          
        </AppWrapper>
        <Footer />
      </body>
      
    </html>
  );
}
