import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/Footer";
import { AppWrapper } from "@/context/page";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import Navbar from "./(components)/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className="mx-10 my-4">
        <body className={inter.className}>
          <AppWrapper>
            {children}
          </AppWrapper>
          {/* <Footer /> */}
        </body>
        
      </html>
    </ClerkProvider>
  );
}
